name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev libgtest-dev build-essential cmake
        # Build and install GTest
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
        
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make
        
    - name: Test
      run: |
        cd build
        ctest --output-on-failure