name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        size: [10, 100, 1000]  # Test different system sizes
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev libgtest-dev build-essential cmake
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib
        
    - name: Build and Test
      run: |
        mkdir build && cd build
        cmake -DSYSTEM_SIZE=${{ matrix.size }} ..
        make
        ctest --output-on-failure --timeout 300  # Increased timeout for large systems